export const headingFonts = [
  {
    id: 1,
    name: "Playfair Display",
    family: "'Playfair Display', serif",
    category: "serif",
    style: "Elegant Serif",
    weight: 700,
  },
  {
    id: 2,
    name: "Montserrat",
    family: "'Montserrat', sans-serif",
    category: "sans-serif",
    style: "Modern Sans",
    weight: 600,
  },
  {
    id: 3,
    name: "Bebas Neue",
    family: "'Bebas Neue', sans-serif",
    category: "display",
    style: "Bold Display",
    weight: 400,
  },
  {
    id: 4,
    name: "Oswald",
    family: "'Oswald', sans-serif",
    category: "sans-serif",
    style: "Strong Sans",
    weight: 600,
  },
  {
    id: 5,
    name: "Merriweather",
    family: "'Merriweather', serif",
    category: "serif",
    style: "Classic Serif",
    weight: 700,
  },
];
export const bodyFonts = [
  {
    id: 1,
    name: "Source Sans Pro",
    family: "'Source Sans 3', sans-serif",
    category: "sans-serif",
    style: "Clean Sans",
    weight: 400,
  },
  {
    id: 2,
    name: "Lora",
    family: "'Lora', serif",
    category: "serif",
    style: "Elegant Serif",
    weight: 400,
  },
  {
    id: 3,
    name: "Open Sans",
    family: "'Open Sans', sans-serif",
    category: "sans-serif",
    style: "Friendly Sans",
    weight: 400,
  },
  {
    id: 4,
    name: "Roboto",
    family: "'Roboto', sans-serif",
    category: "sans-serif",
    style: "Modern Sans",
    weight: 400,
  },
  {
    id: 5,
    name: "Crimson Text",
    family: "'Crimson Text', serif",
    category: "serif",
    style: "Classic Serif",
    weight: 400,
  },
];
